### ISSUE TITLE
Valve status

### ISSUE THREAD

**Issue by kwithus** [j-a-n/python-moehlenhoff-alpha2#1]
Hi
Just noticed that tbis is an official integration now. I would like to switch over, however, the old mptt gave me beside the climate entities also sensors for each valve showing the % the valve is open.
Is it possible to include this to the integration as well?
How about information regarding the battery status of the roomthermostates?

**Comment by timvdsm** [comment]
Also for me this would be really interesting. 

@kwithus also battery status is available through the api? That would be great to have this, next to the valve %, within HA core. 

@j-a-n  would something like that be possible to implement?

**Comment by strandaster** [comment]
> @kwithus also battery status is available through the api? That would be great to have this, next to the valve %, within HA core.

~~The battery status is not available in the XML interface so it will not possible to share it with HA core.~~

I have to correct my answer. The battery status is available (<battery>) but currently I don't know how to interpret the value.

**Comment by kwithus** [comment]
are you sure?

payload.Devices.Device.0.IODEVICE.5.BATTERY.0

does deliver the battery status to me in Nodered

karl-heinz 

Von meinem iPhone gesendet

**Comment by timvdsm** [comment]
Indeed, I also see something mentioned from battery in the xml.
<img width="371" alt="Schermafbeelding 2022-04-30 om 16 41 01" src="https://user-images.githubusercontent.com/14946020/166110089-edf11429-9f53-4c92-9634-7dcb99917ce2.png">

**Comment by kwithus** [comment]
question is: does the core integration use xml or mqtt?
 valve state would be great as well, especially as we talk about floor heating the valve state is of interest 

Von meinem iPhone gesendet

**Comment by j-a-n** [comment]
The integration uses the xml.

**Comment by kwithus** [comment]
i am currently not home, i will look up the xml code later and post it. with xml a lot of info is available 

Von meinem iPhone gesendet

**Comment by kwithus** [comment]
I assume the integration does currently only use the heatarea part
`"HEATAREA":
[{"$":{"nr":"1"},"HEATAREA_NAME":["Gast HK1"],"HEATAREA_MODE":["0"],"T_ACTUAL":["22.6"],"T_ACTUAL_EXT":["22.6"],"T_TARGET":["17.0"],"T_TARGET_BASE":["17.0"],"HEATAREA_STATE":["0"],"PROGRAM_SOURCE":["0"],"PROGRAM_WEEK":["0"],"PROGRAM_WEEKEND":["0"],"PARTY":["0"],"PARTY_REMAININGTIME":["0"],"PRESENCE":["0"],"T_TARGET_MIN":["5.0"],"T_TARGET_MAX":["25.0"],"RPM_MOTOR":["0"],"OFFSET":["1.0"],"T_HEAT_DAY":["21.0"],"T_HEAT_NIGHT":["17.0"],"T_COOL_DAY":["21.0"],"T_COOL_NIGHT":["23.0"],"T_FLOOR_DAY":["3.0"],"HEATINGSYSTEM":["0"],"BLOCK_HC":["0"],"ISLOCKED":["0"],"LOCK_CODE":["455A523F52F509CC"],"LOCK_AVAILABLE":["0"],"LIGHT":["15"],"SENSOR_EXT":["0"],"T_TARGET_ADJUSTABLE":["1"]}, `

More info to be found in the heatctrl part (e.g. valve state = actor_percent)

`"HEATCTRL":
[{"$":{"nr":"1"},"INUSE":["1"],"HEATAREA_NR":["1"],"ACTOR":["0"],"**ACTOR_PERCENT**":["0"],"HEATCTRL_STATE":["0"]},{"$":{"nr":"2"},"INUSE":["1"],"HEATAREA_NR":["2"],"ACTOR":["0"],"ACTOR_PERCENT":["0"],
"HEATCTRL_STATE":["0"]}, `

and in the iodevice part (e.g. battery state of the room thermostat )

`"IODEVICE":
[{"$":{"nr":"1"},"IODEVICE_TYPE":["0"],"IODEVICE_ID":["1"],"IODEVICE_VERS_HW":["1"],"IODEVICE_VERS_SW":["02.02"],"HEATAREA_NR":["1"],"SIGNALSTRENGTH":["2"],"BATTERY":["2"],"IODEVICE_STATE":["0"],"IODEVICE_COMERROR":["0"],"ISON":["1"]}, 

`
Heatctrl and iodevice should probably be separat entities for HA (?)


Also interesting would be to get access to the part with basic info and control on the alpha2 (e.g. vacation dates or program shifting times)

`{"ID":["FBH_Unten"],"TYPE":["EZRCTRL1"],"NAME":["FBH_Unten"],"ORIGIN":["FBH_Unten"],"ERRORCOUNT":["0"],"DATETIME":["2022-05-01T09:53:54"],"DAYOFWEEK":["7"],"TIMEZONE":["2"],"NTPTIMESYNC":["0"],"VERS_SW_STM":["02.02"],"VERS_SW_ETH":["02.02"],"VERS_HW":["01"],"TEMPERATUREUNIT":["0"],"SUMMERWINTER":["1"],"TPS":["0"],"LIMITER":["0"],"MASTERID":["MASTERID"],"CHANGEOVER":["0"],"COOLING":["0"],"MODE":["1"],"OPERATIONMODE_ACTOR":["0"],"ANTIFREEZE":["1"],"ANTIFREEZE_TEMP":["5.0"],"FIRSTOPEN_TIME":["10"],"SMARTSTART":["1"],"ECO_DIFF":["6.0"],"ECO_INPUTMODE":["1"],"ECO_INPUT_STATE":["0"],"T_HEAT_VACATION":["15.0"],"VACATION":[{"VACATION_STATE":["0"],"START_DATE":["[2022-00-00](tel:2022-00-00)"],"START_TIME":["12:00:00"],"END_DATE":["[2022-00-00](tel:2022-00-00)"],"END_TIME":["12:00:00"]}],"NETWORK":[{"MAC":["38:DE:60:01:33:97"],"DHCP":["1"],"IPV6ACTIVE":["0"],"IPV4ACTUAL":["xxx"],"IPV4SET":["192.168.100.100"],"IPV6ACTUAL":[""],"IPV6SET":[""],"NETMASKACTUAL":["255.255.255.0"],"NETMASKSET":["255.255.255.0"],"DNS":["192.168.177.1"],"GATEWAY":["192.168.177.1"]}],"CLOUD":[{"USERID":["xxx"],"PASSWORD":["xxx"],"M2MSERVERPORT":["55555"],"M2MLOCALPORT":["50919"],"M2MHTTPPORT":["50919"],"M2MHTTPSPORT":["55014"],"M2MSERVERADDRESS":["www.ezr-cloud1.de"],"M2MACTIVE":["1"],"M2MSTATE":["Online"]}],"KWLCTRL":[{"KWL_CONTROL_VISIBLE":["0"],"KWL_PRESENT":["0"],"KWL_CONNECTION":["0"],"KWL_URL":["---"],"KWL_PORT":["7777"],"KWL_STATUS":["0"],"KWL_FLOWCTRL":["0"]}],"CODE":[{"EXPERT":["455A521C011C2C64"]}],"PROGRAM":[{"SHIFT_PROGRAM":[{"$":{"nr":"1","shiftingtime":"1"},"START":["00:00"],"END":["00:00"]},{"$":{"nr":"2","shiftingtime":"1"},"START":["04:15"],"END":["22:45"]},{"$":{"nr":"3","shiftingtime":"1"},"START":["00:00"],"END":["24:00"]},{"$":{"nr":"4","shiftingtime":"1"},"START":["06:15"],"END":["21:00"]}]}],"PUMP_OUTPUT":[{"LOCALGLOBAL":["1"],"PUMP_OUTPUT_TYPE":["1"],"PUMP_LEADTIME":["2"],"PUMP_STOPPINGTIME":["2"],"PUMP_OPERATIONMODE":["0"],"MINRUNTIME":["30"],"MINSTANDSTILL":["10"]}],"RELAIS":[{"FUNCTION":["0"],"RELAIS_LEADTIME":["0"],"RELAIS_STOPPINGTIME":["0"],"RELAIS_OPERATIONMODE":["0"]}],"CHANGEOVER_FUNC":[{"CHANGEOVER_FUNC_MODE":["0"]}],"EMERGENCYMODE":[{"EMERGENCYMODE_TIME":["180"],"PWMCYCLE":["15"],"PWMHEAT":["25"],"PWMCOOL":["0"]}],"VALVEPROTECT":[{"VALVEPROTECT_TIME":["14"],"DURATION":["5"]}],"PUMPPROTECT":[{"PUMPPROTECT_TIME":["3"],"DURATION":["5"]}],`


Well, I can give these info, and was able to extract the infos from xml to use it in NodeRed, however no idea how to implement it in an HA integration.
So, thanks in advance to everyone shifting this into HA (entities)

**Comment by kwithus** [comment]
> > @kwithus also battery status is available through the api? That would be great to have this, next to the valve %, within HA core.
> 
> ~The battery status is not available in the XML interface so it will not possible to share it with HA core.~
> 
> I have to correct my answer. The battery status is available () but currently I don't know how to interpret the value.

 0=empty, 1=weak, 2= good
Which is then corresponding to the color for the battery in the alpha2 webui

**Comment by timvdsm** [comment]
Hi this is the correlation between HEATAREA / HEATCTRL / IODEVICE
<img width="622" alt="Schermafbeelding 2022-05-01 om 10 32 21" src="https://user-images.githubusercontent.com/14946020/166138342-f8c77e13-bcb4-45fb-b256-b63671a77531.png">
 
Here is also the xml interface description. Maybe it can help. 
[Alpha2-XML-Interfacedescritption_eng.pdf](https://github.com/j-a-n/python-moehlenhoff-alpha2/files/8598537/Alpha2-XML-Interfacedescritption_eng.pdf)

**Comment by j-a-n** [comment]
Thanks for all the input, but we need to move the discussion into the right place.
This is the repository of the moehlenhoff alpha2 python library, not the moehlenhoff_aplha2 home assistant integration.
Please do not mix up different topics in one thread.
Please open one separate issue for every feature request here:
https://github.com/home-assistant/core/issues/new/choose
