### ISSUE TITLE
Expose function to set date and time

### ISSUE THREAD

**Issue by TitanNano** [j-a-n/python-moehlenhoff-alpha2#2]
According to the linked docs, there is a command to update the base station's date and time settings. My heating's clock is constantly wrong, but I'm too lazy to correct it manually all the time. So, I would appreciate it if I could use this library to automate this task.

**Comment by j-a-n** [comment]
Method `set_datetime` is now available in version 1.3.0.
Example:
``` python
import asyncio
from moehlenhoff_alpha2 import Alpha2Base

async def main():
    base = Alpha2Base("192.168.1.1")
    await base.update_data()
    # Set current date and time in base
    await base.set_datetime()
 
asyncio.run(main())
```

```

**Comment by TitanNano** [comment]
Amazing! 🎉 I would never have expected such an amazingly swift response!

**Comment by j-a-n** [comment]
You caught me at the right moment. 😁

**Comment by TitanNano** [comment]
could you publish 1.3.0 on PyPi?

**Comment by j-a-n** [comment]
Done
